### PR TITLE
Feature dynamics

### PR DESCRIPTION
**Pull request by yhna**
Check with open_manipulator package (feature-dynamics branch)

### CODE REVIEW

**Comment by Ryan-JHShim** [comment]
1. Confirmed working
2. Set gripper -> Send gripper (or send joint -> set joint) in the chain processing file.

**Comment by routiful** [comment]
- open_manipulator_description
  - I modified origin of gripper in urdf
- open_manipulator_lib
  -I modified origin of gripper in OpenManipulator.cpp
- open_manipulator_controller
  - current value is not changed in /open_manipulator/joint_states (solved by @yhna )
- open_manipulator_gazebo
  - Because last commit is not properly working, I have changed pid gains   (**PLEASE CHECK**)
- open_manipulator_moveit
  - 'Execute' failed (solved by @yhna )
- Error occured when draw heart shape 
  - Add shift_offset to make trajectory (solved by @routiful )

**Comment by routiful** [comment]
I added comment on https://github.com/ROBOTIS-GIT/open_manipulator/pull/80

**Comment by Ryan-JHShim** [comment]
1. tested om_chain 
2. SetTool -> SendTool (or SendJoint -> SetJoint) in the processing file.

**Comment by Ryan-JHShim** [comment]
3. In the om_controller.cpp file
priv -> prev

**Pull request merged**
